nxo/nxo/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('portal.urls', namespace='portal')),
    url(r'^admin/', admin.site.urls),
]

nxo/portal/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^list/', views.list, name='list'),
    url(r'^upload/', views.upload, name='upload'),
    url(r'^analyze/(?P<filename>\w{1,50})/$', views.analyze, name='analyze'),
    url(r'^post-to-sizer/(?P<filename>\w{1,50})/$', views.postToSizer, name='postToSizer'),
    url(r'^download/', views.download, name='download'),
]

nxo/portal/models.py
from django.db import models

# Create your models here.


class File(models.Model):
    """Object for file group"""

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted = models.BooleanField(default=False)
    name = models.CharField(max_length=250)
    path = models.FileField(upload_to='uploads/')
    # userid = models.IntegerField()
    computed_ram = models.IntegerField(default=0)
    computed_vcpu = models.IntegerField(default=0)
    computed_capacity = models.IntegerField(default=0)
    user_ram = models.IntegerField(default=0)
    user_vcpu = models.IntegerField(default=0)
    user_capacity = models.IntegerField(default=0)
    ssd_ratio = models.FloatField(default=0.2)

    def update_resources(self):
        vms = Vm.objects.all().filter(file=self)
        self.computed_vcpu = 0
        self.computed_ram = 0
        self.computed_capacity = 0

        for vm in vms:
            self.computed_vcpu += vm.vcpu
            self.computed_ram += vm.ram
            self.computed_capacity += vm.capacity

        if self.user_ram == 0:
            self.user_ram = self.computed_ram

        if self.user_vcpu == 0:
            self.user_vcpu = self.computed_vcpu

        if self.user_capacity == 0:
            self.user_capacity = self.computed_capacity

        self.save()


class Vm(models.Model):
    """VM object"""

    file = models.ForeignKey(File, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    vcpu = models.IntegerField(default=0)
    ram = models.IntegerField(default=0)
    powerstate = models.CharField(max_length=20, default='')
    capacity = models.IntegerField(default=0)
    no_disks = models.IntegerField(default=0)

nxo/portal/views.py
from django.shortcuts import render, redirect

from django_tables2 import RequestConfig

import os
import json

# Create your views here.
#from django.http import HttpResponse
from .upload import FileUpload
from .transform import extract_vms
from .models import File, Vm
from .tables import VmTable

def index(request):
    return render(request, 'index.html')
    #return HttpResponse("Hello, world. You're at the portal index.")

def download(request):
    return render(request, 'download.html')

def list(request):
    files = File.objects.all()
    return render(request, 'list.html')

def upload(request):
    if request.method == 'POST':
        form = FileUpload(request.POST, request.FILES)
        if form.is_valid():
            new_file = form.save()
            extract_vms(new_file)
            return redirect('/analyze/{}'.format(request.POST['name']))
    else:
        form = FileUpload()
    return render(request, 'upload.html', {
        'form': form
    })

def analyze(request, filename=None):
    file = File.objects.filter(name=filename)[0]
    vms = Vm.objects.filter(file=file)
    if file == None:
        print("No file found")
    else:
        table = VmTable(vms)
        RequestConfig(request).configure(table)
        return render(request, 'analyze.html', {
            'table': table,
            'file': file,
            'vms': vms,
            'ram_total_gb': file.computed_ram/1024/1024/1024,
            'capacity_total_gb': file.computed_capacity/1024/1024/1024,
        })

def postToSizer(request, filename=None):
    file = File.objects.filter(name=filename)[0]
    with open('payload.json') as payload_file:
        payload = json.load(payload_file)
        payload['data']['HDD'] = '%.2f' % (((file.computed_capacity/1024/1024/1024/1024)/10)*9)
        payload['data']['RAM'] = '%.2f' % (file.computed_ram/1024/1024/1024)
        payload['data']['SSD'] = '%.2f' % ((file.computed_capacity/1024/1024/1024/1024)/10)
        payload['data']['cpu'] = '%.2f' % ((file.computed_vcpu/6)*2.8)
        payload['data']['vCPUs'] = str(file.computed_vcpu)
        payload['data']['workloadName'] = file.name
    with open('payload.json', 'w') as payload_file:
        json.dump(payload, payload_file, ensure_ascii=False)
    os.system("/data/pushToSizer.sh")
    return redirect("https://services.nutanix.com/#/scenario/MjE1NzMx")

nxo/portal/templates/analyze.html
{% extends 'base.html' %}
{% load render_table from django_tables2 %}
{% block content %}
{% load humanize %}

<div class="container">
    <div class="page-header">
        <h1>Origins Assessment: <small>{{ file.name }}</small></h1>
    </div>

    <div class="panel panel-primary">
    <div class="panel-heading">
        Calculated Workload:
    </div>
        <div class="panel-body">

        <div class="row text-center">
            <div class="col-md-2"><span class="tableIcon"><img src="/static/images/VM_icon.png" width="64px" height="64px" /></span> {{ vms.count  }} VMs</div>
            <div class="col-md-2"><span class="tableIcon"><img src="/static/images/CPU_icon.png" width="64px" height="64px" /></span> {{ file.computed_vcpu|floatformat:"0"|intcomma  }} vCPUs</div>
            <div class="col-md-2"><span class="tableIcon"><img src="/static/images/RAM_icon.png" width="64px" height="64px" /></span> {{ ram_total_gb|floatformat:"0"|intcomma  }} GB RAM</div>
            <div class="col-md-3"><span class="tableIcon"><img src="/static/images/storage_icon.png" width="64px" height="64px" /></span> {{ capacity_total_gb|floatformat:"1"|intcomma  }} GB Disk</div>
            <div class="col-md-3 vcenter">
                <button class="btn btn-primary" style="margin-top:auto;margin-bottom:auto">Recalculate</button>
            </div>
        </div>
</div>
    </div>




    <div class="container-fluid">
        {% render_table table %}
    </div>
    <div class="container-fluid text-center">
        <p>
        <a class="btn btn-lg btn-primary" href="/post-to-sizer/{{ file.name }}">Push Workload to Sizer</a>
        </p>
    </div>
</div>
{% endblock %}

nxo/portal/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Nutanix Xtract Origins</title>

    <!-- Bootstrap -->
    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <link href="/static/css/bootstrap-overrides.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Django table2 -->
    <link rel="stylesheet" href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}" />
  </head>
  <body>


    <div class="navbar navbar-inverse navbar" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><img src="/static/images/logo-n.png" class="logo" style="margin-right:20px" />Xtract Origins</a>
        </div>
        <div class="navbar-collapse collapse">
         <ul class="nav navbar-nav navbar-right">
<li><a href="/download"><span class="glyphicon glyphicon-cloud-download"></span> Download Collector</a></li>
            <li><a href="/upload"><span class="glyphicon glyphicon-plus"></span> New Collection</a></li>
<li><form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form></li>
           <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user pad"></span> jdubois@nutanix.com <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Dashboard</a></li>
                    <li><a href="#">Settings</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Log Out</a></li>


                  </ul>
                </li>
          </ul>

        </div><!--/.navbar-collapse -->
      </div>
    </div>


            {% block content %}
            {% endblock %}





    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/static/js/bootstrap.min.js"></script>

      <div class="footer">
      <div class="container">
        <p class="text-muted">&copy; 2017, Nutanix, Inc.</p>
      </div>
    </div>
  </body>
</html>

nxo/portal/templates/download.html
{% extends 'base.html' %}

{% block content %}


<div class="container">
    <div class="page-header">
        <h1>Download Origins Collection Tool</h1>
    </div>
    <p class="lead">Please download the agent for your platform.</p>
    <div class="row">

        <div class="col-md-6">
            <div class="well-lg">
                <p class="lead">Windows Collection Tool</p>

                <p>Minimum Requirements:<br/>
                    <small>Windows 7 or Server 2012 or higher.</small>
                </p>
                <a href="/static/binaries/NXO_GUI.exe" target="_blank" class="btn btn-primary">Download</a>
            </div>
        </div>
        <div class="col-md-6">

            <div class="well-lg">
                <p class="lead">MacOS Collection Tool</p>
                <p>Minimum Requirements:<br/>
                    <small>OSX</small>
                </p>

                <a href="#" class="btn btn-primary">Download</a>
            </div>

        </div>

    </div>
</div>
{% endblock %}

nxo/portal/templates/index.html
{% extends 'base.html' %}
{% block content %}

<div class="jumbotron">
    <div class="container text-center">
        <h1 class="homepageCallout">Nutanix Xtract: Origins</h1>
        <h2> Origins: your first step in entering the world of the Nutanix Enterprise Cloud.</h2>
        <p><a class="btn btn-primary btn-lg" role="button" href="/download">Download Collection Tool »</a></p>
    </div>
</div>

<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">

    <!-- Three columns of text below the carousel -->
    <div class="row text-center">
        <div class="col-lg-4">
            <img class="img" src="/static/images/nutanix_dataintegritycheck.png" alt="Assess"
                 style="width: 140px; height: 140px;">

            <h2>Assess</h2>
            <p>Assess your actual infrastructure to collect all information and metrics needed to define the best
                infrastructure for you.</p>
            <p><a class="btn btn-default" href="#Collect" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
            <img class="img" src="/static/images/nutanix_richdataanalytics.png" alt="Analyze"
                 style="width: 140px; height: 140px;">
            <h2>Analyze</h2>
            <p>Filter object from assessment data and analyze the real usage from your infrastructure. It will help to
                not oversize the infrastructure.</p>
            <p><a class="btn btn-default" href="#Analyze" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
            <img class="img" src="/static/images/nutanix_servervirtualization.png" alt="Design and Size"
                 style="width: 140px; height: 140px;">
            <h2>Design</h2>
            <p>Push your best-fit needs to define your Next-Gen Infrastructure.</p>
            <p><a class="btn btn-default" href="#Size" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->


    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <div class="row featurette" id="Collect">
        <div class="col-md-7">
            <h2 class="featurette-heading">Collect data about your infrastructure <span class="text-muted">Some more stuff here.</span>
            </h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod
                semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus
                commodo.</p>
        </div>
        <div class="col-md-5">
            <img class="featurette-image img-responsive" src="/static/images/vsphere-looks.png" alt="Collect">
        </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette" id="Analyze">
        <div class="col-md-5">
            <img class="featurette-image img-responsive" src="http://via.placeholder.com/458x458"
                 alt="Xtract Origins Screenshot">
        </div>
        <div class="col-md-7">
            <h2 class="featurette-heading">Analyze your virtualization estate. <span class="text-muted">Pick your targets.</span>
            </h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod
                semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus
                commodo.</p>
        </div>

    </div>


    <hr class="featurette-divider">

    <div class="row featurette" id="Size">

        <div class="col-md-7">
            <h2 class="featurette-heading">Size your next-generation infrastructure. <span class="text-muted">Experience the Nutanix Enterprise Cloud</span>
            </h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod
                semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus
                commodo.</p>
        </div>
        <div class="col-md-5">
            <img class="featurette-image img-responsive" src="/static/images/sizer-looks.png" alt="Sizer">
        </div>
    </div>


    <hr class="featurette-divider">

    <!-- /END THE FEATURETTES -->


</div><!-- /.container -->


{% endblock %}

nxo/portal/templates/layout-onepage.html
{% extends 'base.html' %}


        <div class="container">

    {% block content %}

    {% endblock %}
  </div>

nxo/portal/templates/list.html
{% extends 'base.html' %}

{% block content %}


<div class="container">
    <div class="page-header">
        <h1>List of collected assements</h1>
    </div>
    <p class="lead">List of all the imported files</p>
    <div class="row">
        <div class="col-md-3">
            <div class="well-lg">
                <p class="lead">Windows Collection Tool</p>
                    <p>Minimum Requirements:</p>

                    <a href="#" class="btn btn-primary">Download</a>
            </div>
        </div>
    </div>
</div>
    {% endblock %}

nxo/portal/templates/upload.html
{% extends 'base.html' %}

{% block content %}


<div class="container">
    <div class="page-header">
        <h1>Upload Nutanix Xtract Origins Assessment Package</h1>
    </div>

    <div class="row">

        <div class="col-md-6">
            <div class="well-lg">
                <p class="lead">Please name your project and upload the file generated by the
                    Nutanix Xtract
                    Origins collection tool.</p>


                <form action="/upload/" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="id_name">Assessment Name:</label>
                        <input type="text" name="name" class="form-control" required id="id_name">
                    </div>
                    <div class="form-group">
                        <label for="id_path">File Upload (JSON):</label>
                        <input type="file" name="path" class="form-control" required id="id_path">
                    </div>

                    <button type="submit" name="submit" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-upload"></span> Upload Assessment</button>
                </form>
            </div>
        </div>
        <div class="col-md-6">

            <img class="img-responsive" src="/static/images/origins-logo-large.png" height="456" width="1309"/>

        </div>

    </div>
</div>
    {% endblock %}